### ISSUE TITLE
What pm4py version should I use?

### ISSUE THREAD

**Issue by AdamBanham** [LukasLiss/object-centric-alignments#1]
Hi Lukas,

I read your preprint and found it interesting. I tried to run your code, but you haven't bookmarked a version of pm4py, so I cannot run your notebook (getting-started-example). Could you let me know what version you use so I can see the work in action?

I would recommend checking out[pipenv](https://pipenv.pypa.io/en/latest/) for handling python dependencies or a requirement.txt with bookmarked versions for external modules.

I was on 2.2.30 (which also did not work) but I updated pm4py to 2.7.4 and got the following error in the Juypter notebook:

`
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_12208\3698829705.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/.../git%20projects/object-centric-alignments/~/AppData/Local/Temp/ipykernel_12208/3698829705.py) in 
      1 # core import of the alignment calculation algorithm
----> 2 from algorithm import calculate_oc_alignments
      3 
      4 # imports to load object-centric event logs and discover accepting object-centric Petri net
      5 from localocpa.objects.log.importer.ocel import factory as ocel_import_factory_json

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\algorithm.py in 
----> 1 import localocpa
      2 import helperfunctions
      3 from helperfunctions import FrozenMarking
      4 
      5 # import logging

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\__init__.py in 
----> 1 import localocpa.algo
      2 import localocpa.objects
      3 import localocpa.util
      4 import localocpa.visualization
      5 

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\algo\__init__.py in 
      1 import localocpa.algo.conformance
----> 2 import localocpa.algo.discovery
      3 import localocpa.algo.enhancement
      4 import localocpa.algo.util.retrieval
      5 import localocpa.algo.util

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\algo\discovery\__init__.py in 
----> 1 import localocpa.algo.discovery.enhanced_ocpn
      2 import localocpa.algo.discovery.ocpn

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\algo\discovery\enhanced_ocpn\__init__.py in 
----> 1 from localocpa.algo.discovery.enhanced_ocpn import algorithm

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\algo\discovery\enhanced_ocpn\algorithm.py in 
      1 from localocpa.objects.oc_petri_net.obj import EnhancedObjectCentricPetriNet
----> 2 from localocpa.algo.enhancement.token_replay_based_performance import algorithm as performance_factory
      3 import localocpa.algo.util.retrieval.event_graph.algorithm as event_graph_factory
      4 import localocpa.algo.util.retrieval.correlated_event_graph.algorithm as correlated_event_graph_factory
      5 

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\algo\enhancement\__init__.py in 
      1 import localocpa.algo.enhancement.event_graph_based_performance
----> 2 import localocpa.algo.enhancement.token_replay_based_performance

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\algo\enhancement\token_replay_based_performance\__init__.py in 
----> 1 import localocpa.algo.enhancement.token_replay_based_performance.versions

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\algo\enhancement\token_replay_based_performance\versions\__init__.py in 
----> 1 import localocpa.algo.enhancement.token_replay_based_performance.versions.opera

[c:\Users\...\git](file:///C:/Users/.../git) projects\object-centric-alignments\localocpa\algo\enhancement\token_replay_based_performance\versions\opera.py in 
      9 from statistics import stdev
     10 from localocpa.objects.oc_petri_net.obj import ObjectCentricPetriNet
---> 11 from pm4py.objects.petri.petrinet import PetriNet
     12 from localocpa.algo.enhancement.token_replay_based_performance.util import run_timed_replay, apply_trace, single_element_statistics
     13 from localocpa.objects.log.importer.csv.util import succint_mdl_to_exploded_mdl, clean_frequency, clean_arc_frequency

ModuleNotFoundError: No module named 'pm4py.objects.petri'
`

Cheers,
Adam

**Comment by LukasLiss** [comment]
Hi Adam,
great to hear from you. I just added Pipenv to the project. You can find all the required package versions in the Pipfile.

Best regards,
Lukas

**Comment by AdamBanham** [comment]
Thanks Lukas,

I can run your notebook now with the virtual env. Interesting work.

Cheers,
Adam
